project:
  type: website
  output-dir: docs
  resources:
    - media/**

website:
  title: "Nathaniel Grimes"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
        

format:
  html:
    theme: 
      - default 
      - theme.scss
    toc: true
    include-in-header: "_includes/header.html"


